[colors]
background       = '#f3f3f3ff'
black            = '#282A36'
blue             = '#644AC9'
cursor           = '#282A36'
cyan             = '#036A96'
foreground       = '#1F1F1F'
green            = '#14710A'
magenta          = '#A3144D'
red              = '#CB3A2A'
tabs             = '#E1E4E8'
tabs-active      = '#C9CDD4'
white            = '#1F1F1F'
yellow           = '#846E15'
dim-black        = '#D74B3B'
dim-blue         = '#D74B3B'
dim-cyan         = '#D74B3B'
dim-foreground   = '#D74B3B'
dim-green        = '#D74B3B'
dim-magenta      = '#D74B3B'
dim-red          = '#D74B3B'
dim-white        = '#D74B3B'
dim-yellow       = '#D74B3B'
light-black      = '#928eb6ff'
light-blue       = '#7862D0'
light-cyan       = '#047FB4'
light-foreground = '#1D1D1D'
light-green      = '#198D0C'
light-magenta    = '#BF185A'
light-red        = '#D74C3D'
light-white      = '#2C2B31'
light-yellow     = '#9E841A'
